"""Activations used by the exported PP-OCRv6 graphs.

Hardsigmoid is the squeeze-excite gate. GELU mixes channels in LCNet. ReLU is the stem, the DB head, and IntraCL.

Docs: https://alix559.github.io/solid_lens/activations.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03_activations.ipynb.

# %% ../../nbs/03_activations.ipynb #b5c40cc386fe
from __future__ import annotations

import numpy as np
from max.graph import TensorValue, ops

from ..config import DEVICE, DTYPE


# %% auto #0
__all__ = ['hardsigmoid', 'gelu', 'relu']

# %% ../../nbs/03_activations.ipynb #7ef9eb2b6825
def hardsigmoid(x: TensorValue, alpha: float, beta: float = 0.5) -> TensorValue:
    zero = ops.constant(np.float32(0), DTYPE, device=DEVICE)
    one = ops.constant(np.float32(1), DTYPE, device=DEVICE)
    return ops.min(one, ops.max(zero, x * np.float32(alpha) + np.float32(beta)))


# %% ../../nbs/03_activations.ipynb #dc6699171318
def gelu(x: TensorValue) -> TensorValue:
    return ops.gelu(x)


# %% ../../nbs/03_activations.ipynb #1604177399f8
def relu(x: TensorValue) -> TensorValue:
    return ops.relu(x)

