"""Convolutions whose weights match the ONNX checkpoint layout.

`max.nn.Conv2d(permute=True)` keeps filters in OIHW order, which is how Paddle exported them. A stride-2 kernel-2 transposed convolution does not compile in this MAX build (`num_groups` fails to infer). With the kernel equal to the stride and no padding, the four taps do not overlap, so the transpose is four pointwise mixes interleaved on the spatial axes.

Docs: https://alix559.github.io/solid_lens/conv.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/04_conv.ipynb.

# %% ../../nbs/04_conv.ipynb #ce40bbb95c6e
from __future__ import annotations


# %% auto #0
__all__ = ['same_padding', 'conv2d', 'ConvTranspose2x2', 'nchw_to_nhwc', 'nhwc_to_nchw']

# %% ../../nbs/04_conv.ipynb #0927d8b02eca
def same_padding(kernel: int) -> int:
    return kernel // 2


# %% ../../nbs/04_conv.ipynb #35bab22043da
from max.graph import DeviceRef, TensorValue, Weight, ops
from max.nn.conv import Conv2d
from max.nn.layer import Module

from ..config import DEVICE, DTYPE


# %% ../../nbs/04_conv.ipynb #3193c73c2d65
def conv2d(
    in_channels: int,
    out_channels: int,
    kernel_size: int | tuple[int, int],
    *,
    stride: int | tuple[int, int] = 1,
    padding: int | tuple[int, int, int, int] = 0,
    groups: int = 1,
    bias: bool = True,
    device: DeviceRef = DEVICE,
) -> Conv2d:
    return Conv2d(
        kernel_size,
        in_channels,
        out_channels,
        DTYPE,
        stride=stride,
        padding=padding,
        num_groups=groups,
        device=device,
        has_bias=bias,
        permute=True,
    )


# %% ../../nbs/04_conv.ipynb #561616c7c4bd
class ConvTranspose2x2(Module):
    "Stride-2, kernel-2, pad-0 conv-transpose, written as interleaved matmuls."

    def __init__(self, in_channels: int, out_channels: int, *, bias: bool = True) -> None:
        super().__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.weight = Weight(
            "weight",
            DTYPE,
            (in_channels, out_channels, 2, 2),
            DEVICE,
        )
        self.bias = (
            Weight("bias", DTYPE, (out_channels,), DEVICE) if bias else None
        )

    def __call__(self, x: TensorValue) -> TensorValue:
        x_nhwc = ops.permute(x, [0, 2, 3, 1])
        rows = []
        for iy in range(2):
            pair = []
            for ix in range(2):
                tap = ops.reshape(
                    self.weight[:, :, iy, ix],
                    [self.in_channels, self.out_channels],
                )
                pair.append(ops.matmul(x_nhwc, tap))
            rows.append(_interleave(pair[0], pair[1], axis=2))
        y = ops.permute(_interleave(rows[0], rows[1], axis=1), [0, 3, 1, 2])
        if self.bias is not None:
            y = y + ops.reshape(self.bias, [1, self.out_channels, 1, 1])
        return y


# %% ../../nbs/04_conv.ipynb #004a66d5fdd7
def _interleave(a: TensorValue, b: TensorValue, axis: int) -> TensorValue:
    "Interleave two NHWC tensors along height (axis 1) or width (axis 2)."
    stacked = ops.concat(
        [ops.unsqueeze(a, axis + 1), ops.unsqueeze(b, axis + 1)],
        axis=axis + 1,
    )
    shape = stacked.shape
    if axis == 2:
        return ops.reshape(stacked, [shape[0], shape[1], shape[2] * 2, shape[4]])
    return ops.reshape(stacked, [shape[0], shape[1] * 2, shape[3], shape[4]])


# %% ../../nbs/04_conv.ipynb #343ccf423625
def nchw_to_nhwc(x: TensorValue) -> TensorValue:
    return ops.permute(x, [0, 2, 3, 1])


# %% ../../nbs/04_conv.ipynb #628880fd37ae
def nhwc_to_nchw(x: TensorValue) -> TensorValue:
    return ops.permute(x, [0, 3, 1, 2])

