"""Inference DB head, and the nearest upsample the detection neck shares.

Two stride-2 transposed convolutions restore the input resolution. The probability map is a sigmoid over one channel.

Docs: https://alix559.github.io/solid_lens/neck.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/06_neck.ipynb.

# %% ../../nbs/06_neck.ipynb #1508518c030e
from __future__ import annotations

from max.graph import TensorValue, ops
from max.nn.layer import Module

from .activations import relu
from .conv import ConvTranspose2x2, conv2d


# %% auto #0
__all__ = ['DBHead']

# %% ../../nbs/06_neck.ipynb #04baf5f8803e
def _upsample(x: TensorValue, factor: int) -> TensorValue:
    if factor == 1:
        return x
    shape = x.shape
    return ops.resize_nearest(
        x,
        [shape[0], shape[1], shape[2] * factor, shape[3] * factor],
        coordinate_transform_mode=2,
        round_mode=2,
    )


# %% ../../nbs/06_neck.ipynb #b30ce31c72eb
class DBHead(Module):
    def __init__(self, in_channels: int, hidden: int) -> None:
        super().__init__()
        self.conv = conv2d(in_channels, hidden, 3, padding=1, bias=True)
        self.up1 = ConvTranspose2x2(hidden, hidden, bias=True)
        self.up2 = ConvTranspose2x2(hidden, 1, bias=True)

    def __call__(self, x: TensorValue) -> TensorValue:
        x = relu(self.conv(x))
        x = relu(self.up1(x))
        return ops.sigmoid(self.up2(x))

