"""EncoderWithLightSVTR, the PP-OCRv6 medium recognition neck.

The exported graph is the inference network. Dropout is gone. Each Conv-BN-Swish stays unfused, and each LayerNorm is a learned scale and bias. Two global transformer blocks sit between a 1×7 depthwise conv and an additive 1×1 skip. The NRTR decoder is not in the checkpoint.

Docs: https://alix559.github.io/solid_lens/svtr.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/08_svtr.ipynb.

# %% ../../nbs/08_svtr.ipynb #64be0905986b
from __future__ import annotations

import numpy as np
from max.graph import TensorValue, Weight, ops
from max.nn.layer import Module
from max.nn.linear import Linear

from ..config import DEVICE, DTYPE
from .conv import conv2d
from .lcnet import BatchNorm


# %% auto #0
__all__ = ['LayerNorm', 'ConvBNSwish', 'LocalMixer', 'SVTRBlock', 'LightSVTR']

# %% ../../nbs/08_svtr.ipynb #8bc350ce33d7
class LayerNorm(Module):
    def __init__(self, channels: int, eps: float) -> None:
        super().__init__()
        self.eps = eps
        self.weight = Weight("weight", DTYPE, (channels,), DEVICE)
        self.bias = Weight("bias", DTYPE, (channels,), DEVICE)

    def __call__(self, x: TensorValue) -> TensorValue:
        return ops.layer_norm(x, self.weight, self.bias, epsilon=self.eps)


# %% ../../nbs/08_svtr.ipynb #768afb0cac13
class ConvBNSwish(Module):
    "1x1 projection used by the skip and the channel reduction."

    def __init__(self, in_channels: int, out_channels: int, eps: float) -> None:
        super().__init__()
        self.conv = conv2d(in_channels, out_channels, 1, bias=False)
        self.bn = BatchNorm(out_channels, eps)

    def __call__(self, x: TensorValue) -> TensorValue:
        return ops.silu(self.bn(self.conv(x)))


# %% ../../nbs/08_svtr.ipynb #a294e9356862
class LocalMixer(Module):
    "1xk depthwise conv along the text width, added back onto its input."

    def __init__(self, channels: int, kernel: int, eps: float) -> None:
        super().__init__()
        pad = kernel // 2
        self.conv = conv2d(
            channels,
            channels,
            (1, kernel),
            padding=(0, 0, pad, pad),
            groups=channels,
            bias=False,
        )
        self.bn = BatchNorm(channels, eps)

    def __call__(self, x: TensorValue) -> TensorValue:
        return x + ops.silu(self.bn(self.conv(x)))


# %% ../../nbs/08_svtr.ipynb #55daf33c57ee
class SVTRBlock(Module):
    "Pre-norm global attention and a Swish MLP. Dropout is identity here."

    def __init__(self, dim: int, num_heads: int, mlp_ratio: float, eps: float) -> None:
        super().__init__()
        if dim % num_heads != 0:
            raise ValueError(f"{dim} channels is not divisible by {num_heads} heads")
        self.num_heads = num_heads
        self.head_dim = dim // num_heads
        self.norm1 = LayerNorm(dim, eps)
        self.qkv = Linear(dim, dim * 3, DTYPE, DEVICE, has_bias=True)
        self.proj = Linear(dim, dim, DTYPE, DEVICE, has_bias=True)
        self.norm2 = LayerNorm(dim, eps)
        hidden = int(dim * mlp_ratio)
        self.fc1 = Linear(dim, hidden, DTYPE, DEVICE, has_bias=True)
        self.fc2 = Linear(hidden, dim, DTYPE, DEVICE, has_bias=True)

    def __call__(self, x: TensorValue) -> TensorValue:
        x = x + self._attend(self.norm1(x))
        return x + self.fc2(ops.silu(self.fc1(self.norm2(x))))

    def _attend(self, x: TensorValue) -> TensorValue:
        # x is (batch, width, channels). The scale is 1/sqrt(head_dim) and
        # multiplies q only, matching the exported graph.
        batch, width, _ = x.shape[0], x.shape[1], x.shape[2]
        heads = self.num_heads
        head_dim = self.head_dim
        mixed = ops.permute(
            ops.reshape(self.qkv(x), [batch, width, 3, heads, head_dim]),
            [2, 0, 3, 1, 4],
        )
        query, key, value = ops.split(mixed, [1, 1, 1], axis=0)
        scale = ops.constant(np.float32(head_dim**-0.5), DTYPE, device=DEVICE)
        query = ops.squeeze(query, axis=0) * scale
        key = ops.squeeze(key, axis=0)
        value = ops.squeeze(value, axis=0)
        scores = ops.softmax(
            ops.matmul(query, ops.permute(key, [0, 1, 3, 2])),
            axis=-1,
        )
        context = ops.matmul(scores, value)
        context = ops.permute(context, [0, 2, 1, 3])
        context = ops.reshape(context, [batch, width, heads * head_dim])
        return self.proj(context)


# %% ../../nbs/08_svtr.ipynb #56cf4de461b8
class LightSVTR(Module):
    "Local conv, global blocks, then an additive skip of the backbone features."

    def __init__(
        self,
        in_channels: int,
        dim: int,
        depth: int,
        num_heads: int,
        mlp_ratio: float,
        local_kernel: int,
        eps: float,
        final_eps: float,
    ) -> None:
        super().__init__()
        # Skip is defined first because the exporter emits it first.
        self.skip = ConvBNSwish(in_channels, dim, eps)
        self.reduce = ConvBNSwish(in_channels, dim, eps)
        self.local = LocalMixer(dim, local_kernel, eps)
        self.depth = depth
        for index in range(depth):
            setattr(self, f"block{index}", SVTRBlock(dim, num_heads, mlp_ratio, eps))
        self.norm = LayerNorm(dim, final_eps)

    def __call__(self, x: TensorValue) -> TensorValue:
        # x is NCHW with height 1. Attention runs on (batch, width, channels).
        skip = _as_sequence(self.skip(x))
        hidden = self.local(self.reduce(x))
        sequence = _as_sequence(hidden)
        for index in range(self.depth):
            sequence = getattr(self, f"block{index}")(sequence)
        return self.norm(sequence) + skip


# %% ../../nbs/08_svtr.ipynb #71076824b986
def _as_sequence(x: TensorValue) -> TensorValue:
    return ops.permute(ops.squeeze(x, axis=2), [0, 2, 1])

