"""PP-OCRv6 medium, as the PaddleOCR training configs describe it.

Detection uses PPLCNetV4, a RepLKPAN neck with IntraCL, and the inference DB head. Recognition uses the same backbone with height-only downsampling, then a LightSVTR neck and a CTC head. The NRTR head exists only while training, so it is not in these graphs.

Docs: https://alix559.github.io/solid_lens/config.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_config.ipynb.

# %% ../nbs/01_config.ipynb #427bf8c8e9ec
from __future__ import annotations

from dataclasses import dataclass


# %% auto #0
__all__ = ['Block', 'DET_BLOCKS', 'REC_BLOCKS', 'DEVICE', 'DTYPE', 'DetectorConfig', 'RecognizerConfig']

# %% ../nbs/01_config.ipynb #6915d53f4ab6
# kernel, in_channels, out_channels, stride, use_se
Block = tuple[int, int, int, int | tuple[int, int], bool]


# %% ../nbs/01_config.ipynb #2fa1d0595be7
DET_BLOCKS: dict[str, list[Block]] = {
    "s1": [(3, 128, 128, 1, True), (3, 128, 128, 1, False)],
    "s2": [
        (3, 128, 256, 2, False),
        (3, 256, 256, 1, True),
        (3, 256, 256, 1, False),
    ],
    "s3": [
        (3, 256, 512, 2, False),
        (3, 512, 512, 1, True),
        (3, 512, 512, 1, False),
        (3, 512, 512, 1, True),
        (3, 512, 512, 1, False),
    ],
    "s4": [
        (3, 512, 896, 2, False),
        (3, 896, 896, 1, True),
        (3, 896, 896, 1, False),
    ],
}


# %% ../nbs/01_config.ipynb #1dd5c8e787b3
REC_BLOCKS: dict[str, list[Block]] = {
    "b2": [(3, 128, 128, 1, True)],
    "b3": [
        (3, 128, 256, 1, False),
        (3, 256, 256, 1, False),
        (3, 256, 256, 1, True),
    ],
    "b4": [
        (3, 256, 512, (2, 1), False),
        (3, 512, 512, 1, True),
        (3, 512, 512, 1, False),
        (3, 512, 512, 1, True),
        (3, 512, 512, 1, False),
        (3, 512, 512, 1, True),
        (3, 512, 512, 1, False),
    ],
    "b5": [
        (3, 512, 768, (2, 1), False),
        (3, 768, 768, 1, True),
        (3, 768, 768, 1, False),
    ],
}


# %% ../nbs/01_config.ipynb #2b2c8fee73b4
@dataclass(frozen=True)
class DetectorConfig:
    stem_mid: int = 64
    stem_out: int = 128
    # RepLKPAN projects every level to this width, then to width // 4.
    fpn_channels: int = 256
    replk_kernel: int = 9
    head_channels: int = 64
    se_alpha: float = 1.0 / 6.0


# %% ../nbs/01_config.ipynb #e1ab761bbfe3
@dataclass(frozen=True)
class RecognizerConfig:
    stem_mid: int = 64
    stem_out: int = 128
    backbone_channels: int = 768
    svtr_dim: int = 192
    svtr_depth: int = 2
    svtr_heads: int = 8
    mlp_ratio: float = 4.0
    local_kernel: int = 7
    num_classes: int = 18710
    image_height: int = 48
    image_width: int = 320
    se_alpha: float = 1.0 / 6.0
    # Conv batch-norm and the transformer block norms both use 1e-5.
    # The norm after the last block uses 1e-6.
    bn_eps: float = 1e-5
    final_norm_eps: float = 1e-6


# %% ../nbs/01_config.ipynb #56f8e88cf60d
from max.dtype import DType
from max.graph import DeviceRef

DEVICE = DeviceRef.CPU()
DTYPE = DType.float32

