"""Find the checkout that holds the weights.

Checkpoints and `requirements.txt` live next to `pixi.toml`, not inside the package directory.

Docs: https://alix559.github.io/solid_lens/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% ../nbs/00_core.ipynb #894cea8a155c
from __future__ import annotations

from pathlib import Path


# %% auto #0
__all__ = ['repo_root']

# %% ../nbs/00_core.ipynb #163acab1f006
def repo_root() -> Path:
    "Checkout that holds `models/`, `pixi.toml`, and `requirements.txt`."
    starts = []
    file = globals().get("__file__")
    if file: starts.append(Path(file).resolve().parent)
    starts.append(Path.cwd())
    for start in starts:
        for parent in (start, *start.parents):
            if (parent / "pixi.toml").is_file() and (parent / "requirements.txt").is_file():
                return parent
    raise FileNotFoundError("solid_lens checkout (pixi.toml) was not found")

