"""PP-OCRv6 medium text detector.

Stem, four LCNet stages, RepLKPAN, and the DB head. The four stage outputs are the neck's fine, mid, low, and coarse maps. Their widths are 128, 256, 512, and 896.

Docs: https://alix559.github.io/solid_lens/detector.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_detector.ipynb.

# %% ../nbs/09_detector.ipynb #4ca9967fe45f
from __future__ import annotations

from max.graph import TensorValue
from max.nn.layer import Module

from .config import DET_BLOCKS, DetectorConfig
from .layers.lcnet import DetStem, stage
from .layers.neck import DBHead
from .layers.pan import RepLKPAN


# %% auto #0
__all__ = ['PPOCRV6Detector']

# %% ../nbs/09_detector.ipynb #27ecf53a4042
class PPOCRV6Detector(Module):
    def __init__(self, config: DetectorConfig | None = None) -> None:
        super().__init__()
        config = config or DetectorConfig()
        self.stem = DetStem(config.stem_mid, config.stem_out)
        self.stage1 = stage(DET_BLOCKS["s1"], config.se_alpha, bias=True)
        self.stage2 = stage(DET_BLOCKS["s2"], config.se_alpha, bias=True)
        self.stage3 = stage(DET_BLOCKS["s3"], config.se_alpha, bias=True)
        self.stage4 = stage(DET_BLOCKS["s4"], config.se_alpha, bias=True)
        self.neck = RepLKPAN((128, 256, 512, 896), config.fpn_channels, config.replk_kernel)
        self.head = DBHead(config.fpn_channels, config.head_channels)

    def __call__(self, x: TensorValue) -> TensorValue:
        fine = self.stage1(self.stem(x))
        mid = self.stage2(fine)
        low = self.stage3(mid)
        coarse = self.stage4(low)
        return self.head(self.neck((fine, mid, low, coarse)))

