"""Fetch the ONNX checkpoints named in `requirements.txt`.

`requirements.txt` is a manifest, not a pip file. Each line is a filename and a URL. The files land in `models/` at the checkout root.

Docs: https://alix559.github.io/solid_lens/download.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/14_download.ipynb.

# %% ../nbs/14_download.ipynb #3fffe55a628f
from __future__ import annotations

from pathlib import Path
from urllib.request import Request, urlopen

from .core import repo_root


# %% auto #0
__all__ = ['ROOT', 'MODELS', 'REQUIREMENTS', 'download', 'main']

# %% ../nbs/14_download.ipynb #c56b12c51e0e
ROOT = repo_root()
MODELS = ROOT / "models"
REQUIREMENTS = ROOT / "requirements.txt"


# %% ../nbs/14_download.ipynb #e70617670b48
def _entries() -> list[tuple[str, str]]:
    entries = []
    for line in REQUIREMENTS.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name, url = line.split()
        entries.append((name, url))
    return entries


# %% ../nbs/14_download.ipynb #afdbd8859272
def download(name: str, url: str) -> None:
    dest = MODELS / name
    if dest.exists():
        print(f"exists {dest.name}")
        return
    print(f"downloading {dest.name}")
    request = Request(url, headers={"User-Agent": "solid_lens"})
    with urlopen(request) as response, dest.open("wb") as out:
        while chunk := response.read(1 << 20):
            out.write(chunk)
    print(f"wrote {dest.name} ({dest.stat().st_size} bytes)")


# %% ../nbs/14_download.ipynb #1aa757ac79cd
def main() -> None:
    MODELS.mkdir(exist_ok=True)
    for name, url in _entries():
        download(name, url)


# %% ../nbs/14_download.ipynb #9ce74e78aad3
if __name__ == "__main__":
    main()

