"""Compile the PP-OCRv6 medium modules and bind their checkpoints.

The detector is one graph per input shape, because both sides are fixed and must be multiples of 32. The recognizer is one graph, 48×320. A cache directory of compiled MEFs is reused; an empty directory is where a new compilation is written.

Docs: https://alix559.github.io/solid_lens/model.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/12_model.ipynb.

# %% ../nbs/12_model.ipynb #4d19da25ebf8
from __future__ import annotations

from pathlib import Path

from max.driver import CPU
from max.engine import InferenceSession
from max.graph import Graph, TensorType

from .config import DEVICE, DTYPE, RecognizerConfig
from .core import repo_root
from .detector import PPOCRV6Detector
from .recognizer import PPOCRV6Recognizer
from .weights import load_checkpoint


# %% auto #0
__all__ = ['ROOT', 'compile_detector', 'compile_recognizer']

# %% ../nbs/12_model.ipynb #c73e0764b2d3
ROOT = repo_root()


# %% ../nbs/12_model.ipynb #15d7158c3181
def _session(cache_dir: Path | None) -> InferenceSession:
    kwargs = {}
    if cache_dir is not None:
        cache_dir.mkdir(parents=True, exist_ok=True)
        if any(cache_dir.iterdir()):
            kwargs["precompiled_mefs"] = cache_dir
        else:
            kwargs["export_mefs"] = cache_dir
    return InferenceSession(devices=[CPU()], **kwargs)


# %% ../nbs/12_model.ipynb #e58c1ff7dde1
def _compile(module, shape: list[int], name: str, cache_dir: Path | None):
    graph = Graph(name, input_types=[TensorType(DTYPE, shape, device=DEVICE)])
    with graph:
        graph.output(module(graph.inputs[0].tensor))
    weights = module.state_dict()
    return _session(cache_dir).load(graph, weights_registry=weights)


# %% ../nbs/12_model.ipynb #ae3e9093b3d1
def compile_detector(
    size: int | None = None,
    cache_dir: Path | None = None,
    *,
    height: int | None = None,
    width: int | None = None,
):
    "Compile the detector for one input shape."
    if height is None and width is None:
        if size is None:
            raise ValueError("pass size, or height and width")
        height = width = size
    elif height is None or width is None:
        raise ValueError("height and width are set together")
    if height % 32 or width % 32:
        raise ValueError("detector sides must be multiples of 32")
    module = PPOCRV6Detector()
    load_checkpoint(module, ROOT / "models" / "medium_det.onnx")
    return _compile(
        module,
        [1, 3, height, width],
        f"ppocrv6_medium_det_{height}x{width}",
        cache_dir,
    )


# %% ../nbs/12_model.ipynb #84d4b2b3f92a
def compile_recognizer(cache_dir: Path | None = None):
    config = RecognizerConfig()
    module = PPOCRV6Recognizer(config)
    load_checkpoint(module, ROOT / "models" / "medium_rec.onnx")
    return _compile(
        module,
        [1, 3, config.image_height, config.image_width],
        "ppocrv6_medium_rec",
        cache_dir,
    )

