"""Read a page with the PP-OCRv6 medium detector and recognizer.

Pages are resized and boxes are read off the detector map the same way as PaddleOCR: keep the aspect ratio, then take DB contours, a minimum-area rectangle, and an unclip. Recognition is CTC over the LightSVTR sequence. Compilation stays inside `main`, so the geometry below can be read on its own.

Docs: https://alix559.github.io/solid_lens/ocr.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/13_ocr.ipynb.

# %% ../nbs/13_ocr.ipynb #799976f4f788
from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

from .core import repo_root


# %% auto #0
__all__ = ['ROOT', 'DET_LIMIT_SIDE_LEN', 'DET_LIMIT_TYPE', 'DET_MAX_SIDE_LIMIT', 'DET_THRESH', 'DET_BOX_THRESH',
           'DET_UNCLIP_RATIO', 'DET_MAX_CANDIDATES', 'DET_MIN_SIZE', 'DET_MEAN', 'DET_STD', 'detection_hw',
           'load_charset', 'load_image', 'resize_hwc', 'det_input', 'boxes_from_bitmap', 'recognize_crop',
           'detect_boxes', 'read_page', 'draw_boxes', 'save_rgb', 'main']

# %% ../nbs/13_ocr.ipynb #cc245abb1da2
ROOT = repo_root()


# %% ../nbs/13_ocr.ipynb #7deda26e4527
DET_LIMIT_SIDE_LEN = 64
DET_LIMIT_TYPE = "min"
DET_MAX_SIDE_LIMIT = 4000
DET_THRESH = 0.3
DET_BOX_THRESH = 0.6
DET_UNCLIP_RATIO = 1.5
DET_MAX_CANDIDATES = 3000
DET_MIN_SIZE = 3


# %% ../nbs/13_ocr.ipynb #ee51d5dbc65f
def detection_hw(
    height: int, # Page height, in pixels
    width: int, # Page width, in pixels
    limit_side_len: int = DET_LIMIT_SIDE_LEN, # Side the limit type compares against
    limit_type: str = DET_LIMIT_TYPE, # `min`, `max`, or `resize_long`
    max_side_limit: int = DET_MAX_SIDE_LIMIT,
) -> tuple[int, int]:
    "Detector height and width. Same rule as PaddleOCR `DetResizeForTest` type 0."
    if limit_type == "max":
        ratio = float(limit_side_len) / max(height, width) if max(height, width) > limit_side_len else 1.0
    elif limit_type == "min":
        ratio = float(limit_side_len) / min(height, width) if min(height, width) < limit_side_len else 1.0
    elif limit_type == "resize_long":
        ratio = float(limit_side_len) / max(height, width)
    else:
        raise ValueError(f"unsupported limit type {limit_type}")
    resize_h = int(height * ratio)
    resize_w = int(width * ratio)
    if max(resize_h, resize_w) > max_side_limit:
        fitted = float(max_side_limit) / max(resize_h, resize_w)
        resize_h = int(resize_h * fitted)
        resize_w = int(resize_w * fitted)
    resize_h = max(int(round(resize_h / 32) * 32), 32)
    resize_w = max(int(round(resize_w / 32) * 32), 32)
    return resize_h, resize_w


# %% ../nbs/13_ocr.ipynb #eb2f0e4cfc4b
def _ctc_decode(ids: list[int], charset: list[str]) -> str:
    text = []
    previous = -1
    for index in ids:
        if index != 0 and index != previous:
            text.append(charset[index - 1])
        previous = index
    return "".join(text).strip()


# %% ../nbs/13_ocr.ipynb #696efda4c344
import cv2
import numpy as np
import pyclipper
from PIL import Image


# %% ../nbs/13_ocr.ipynb #01c1eac99012
DET_MEAN = np.array([0.485, 0.456, 0.406], np.float32)
DET_STD = np.array([0.229, 0.224, 0.225], np.float32)


# %% ../nbs/13_ocr.ipynb #727adb50ad72
def load_charset(path: Path, *, add_space: bool = False) -> list[str]:
    chars = path.read_text().splitlines()
    if add_space:
        chars.append(" ")
    return chars


# %% ../nbs/13_ocr.ipynb #c5b0f3cb7474
def load_image(path: Path) -> np.ndarray:
    "Return an RGB uint8 image."
    with Image.open(path) as image:
        return np.ascontiguousarray(image.convert("RGB"))


# %% ../nbs/13_ocr.ipynb #8aa9fc9e5365
def resize_hwc(image: np.ndarray, out_h: int, out_w: int) -> np.ndarray:
    src_h, src_w = image.shape[:2]
    if (src_h, src_w) == (out_h, out_w):
        return image
    y = (np.arange(out_h, dtype=np.float32) + 0.5) * src_h / out_h - 0.5
    x = (np.arange(out_w, dtype=np.float32) + 0.5) * src_w / out_w - 0.5
    y = np.clip(y, 0, src_h - 1)
    x = np.clip(x, 0, src_w - 1)
    y0 = np.floor(y).astype(np.int32)
    x0 = np.floor(x).astype(np.int32)
    y1 = np.clip(y0 + 1, 0, src_h - 1)
    x1 = np.clip(x0 + 1, 0, src_w - 1)
    wy = (y - y0).astype(np.float32)[:, None, None]
    wx = (x - x0).astype(np.float32)[None, :, None]
    top = image[y0][:, x0] * (1 - wx) + image[y0][:, x1] * wx
    bot = image[y1][:, x0] * (1 - wx) + image[y1][:, x1] * wx
    return (top * (1 - wy) + bot * wy).astype(image.dtype)


# %% ../nbs/13_ocr.ipynb #2620452d32f1
def det_input(image_rgb: np.ndarray, out_h: int, out_w: int) -> np.ndarray:
    "Resize like Paddle and normalize to a BGR NCHW tensor."
    resized = cv2.resize(image_rgb, (out_w, out_h))
    bgr = resized[:, :, ::-1].astype(np.float32)
    normalized = (bgr / 255.0 - DET_MEAN) / DET_STD
    return np.ascontiguousarray(np.transpose(normalized, (2, 0, 1))[None], dtype=np.float32)


# %% ../nbs/13_ocr.ipynb #12f438fce272
def _mini_boxes(contour: np.ndarray) -> tuple[list[list[float]], float]:
    "Four corners of the minimum-area rectangle, and its shorter side."
    rect = cv2.minAreaRect(contour)
    points = sorted(cv2.boxPoints(rect).tolist(), key=lambda point: point[0])
    index_1, index_4 = (0, 1) if points[1][1] > points[0][1] else (1, 0)
    index_2, index_3 = (2, 3) if points[3][1] > points[2][1] else (3, 2)
    box = [points[index_1], points[index_2], points[index_3], points[index_4]]
    return box, min(rect[1])


# %% ../nbs/13_ocr.ipynb #90ea2aacacf5
def _box_score_fast(bitmap: np.ndarray, box: np.ndarray) -> float:
    "Mean detector score inside the quadrilateral."
    height, width = bitmap.shape[:2]
    xmin = max(0, min(math.floor(float(box[:, 0].min())), width - 1))
    xmax = max(0, min(math.ceil(float(box[:, 0].max())), width - 1))
    ymin = max(0, min(math.floor(float(box[:, 1].min())), height - 1))
    ymax = max(0, min(math.ceil(float(box[:, 1].max())), height - 1))
    mask = np.zeros((ymax - ymin + 1, xmax - xmin + 1), np.uint8)
    shifted = box.copy()
    shifted[:, 0] -= xmin
    shifted[:, 1] -= ymin
    cv2.fillPoly(mask, shifted.reshape(1, -1, 2).astype(np.int32), 1)
    return float(cv2.mean(bitmap[ymin : ymax + 1, xmin : xmax + 1], mask)[0])


# %% ../nbs/13_ocr.ipynb #bc921f833d46
def _unclip(box: np.ndarray, unclip_ratio: float) -> np.ndarray:
    "Offset the polygon by `area * ratio / perimeter`, as `DBPostProcess` does."
    area = cv2.contourArea(box)
    length = cv2.arcLength(box, True)
    if length <= 0:
        return np.zeros((0, 2), np.float32)
    offset = pyclipper.PyclipperOffset()
    offset.AddPath(box, pyclipper.JT_ROUND, pyclipper.ET_CLOSEDPOLYGON)
    expanded = offset.Execute(area * unclip_ratio / length)
    if not expanded:
        return np.zeros((0, 2), np.float32)
    try:
        return np.array(expanded)
    except ValueError:
        return np.array(expanded[0])


# %% ../nbs/13_ocr.ipynb #5e51b3d0f4d9
def boxes_from_bitmap(
    prob: np.ndarray,
    dest_width: int,
    dest_height: int,
    *,
    thresh: float = DET_THRESH,
    box_thresh: float = DET_BOX_THRESH,
    unclip_ratio: float = DET_UNCLIP_RATIO,
    max_candidates: int = DET_MAX_CANDIDATES,
) -> list[tuple[int, int, int, int, float]]:
    "PaddleOCR `DBPostProcess` quads, returned as axis-aligned boxes."
    bitmap = prob > thresh
    height, width = bitmap.shape
    width_scale = dest_width / width
    height_scale = dest_height / height
    found = cv2.findContours((bitmap.astype(np.uint8) * 255), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
    contours = found[0] if len(found) == 2 else found[1]
    boxes: list[tuple[int, int, int, int, float]] = []
    for contour in contours[:max_candidates]:
        points, short_side = _mini_boxes(contour)
        if short_side < DET_MIN_SIZE:
            continue
        points_arr = np.asarray(points, dtype=np.float32)
        score = _box_score_fast(prob, points_arr)
        if score < box_thresh:
            continue
        expanded = _unclip(points_arr, unclip_ratio)
        if expanded.size == 0:
            continue
        expanded, short_side = _mini_boxes(expanded.reshape(-1, 1, 2))
        if short_side < DET_MIN_SIZE + 2:
            continue
        quad = np.asarray(expanded, dtype=np.float64)
        quad[:, 0] = np.clip(np.round(quad[:, 0] * width_scale), 0, dest_width)
        quad[:, 1] = np.clip(np.round(quad[:, 1] * height_scale), 0, dest_height)
        left = int(quad[:, 0].min())
        top = int(quad[:, 1].min())
        right = int(quad[:, 0].max())
        bottom = int(quad[:, 1].max())
        if right <= left or bottom <= top:
            continue
        boxes.append((left, top, right, bottom, score))
    boxes.sort(key=lambda box: (box[1], box[0]))
    return boxes


# %% ../nbs/13_ocr.ipynb #0c31cd22bd35
def _recognize_ids(model, image_rgb: np.ndarray) -> list[int]:
    "Run one crop that already fits the 320-wide recognizer."
    height, width = image_rgb.shape[:2]
    resized_w = int(np.ceil(48 * width / height))
    resized_w = max(8, min(320, resized_w))
    resized = resize_hwc(image_rgb, 48, resized_w).astype(np.float32)
    bgr = resized[:, :, ::-1]
    normalized = np.transpose((bgr / 255.0 - 0.5) / 0.5, (2, 0, 1))
    tensor = np.zeros((1, 3, 48, 320), np.float32)
    tensor[0, :, :, :resized_w] = normalized
    tensor = np.ascontiguousarray(tensor)
    probs = model.execute(tensor)[0].to_numpy()[0]
    # The recognizer downsamples width by 8, so padding past resized_w is blank.
    valid = max(1, resized_w // 8)
    return [int(index) for index in probs.argmax(axis=-1)[:valid]]


# %% ../nbs/13_ocr.ipynb #8278a65188f2
def recognize_crop(model, image_rgb: np.ndarray, charset: list[str]) -> str:
    height, width = image_rgb.shape[:2]
    if height < 2 or width < 2:
        return ""
    fitted = int(np.ceil(48 * width / height))
    if fitted <= 320:
        return _ctc_decode(_recognize_ids(model, image_rgb), charset)
    # A long line squashed into 320 columns loses characters. Slide a window
    # whose kept timesteps abut, and drop the edges where the crop has no context.
    drop = 5
    stride_net = (40 - 2 * drop) * 8
    window = max(8, int(round(320 * height / 48)))
    stride = max(4, int(round(stride_net * height / 48)))
    merged: list[int] = []
    x = 0
    first = True
    while x < width:
        piece = image_rgb[:, x : min(width, x + window)]
        seq = _recognize_ids(model, piece)
        last = x + window >= width
        if first and last:
            use = seq
        elif first:
            use = seq[:-drop] if len(seq) > drop else seq
        elif last:
            use = seq[drop:] if len(seq) > drop else seq
        elif len(seq) > 2 * drop:
            use = seq[drop:-drop]
        else:
            use = seq
        merged.extend(use)
        if last:
            break
        x += stride
        first = False
    return _ctc_decode(merged, charset)


# %% ../nbs/13_ocr.ipynb #b8d74d0512d3
def detect_boxes(image_rgb: np.ndarray, det_model) -> list[tuple[int, int, int, int, float]]:
    "Text boxes in original pixels, from one forward pass at the PaddleOCR det size."
    height, width = image_rgb.shape[:2]
    out_h, out_w = detection_hw(height, width)
    prob = det_model.execute(det_input(image_rgb, out_h, out_w))[0].to_numpy()[0, 0]
    return boxes_from_bitmap(prob, width, height)


# %% ../nbs/13_ocr.ipynb #bdd0557d4e25
def read_page(
    image_rgb: np.ndarray,
    det_model,
    rec_model,
    charset: list[str],
) -> list[tuple[str, float, int, int, int, int]]:
    lines = []
    for left, top, right, bottom, score in detect_boxes(image_rgb, det_model):
        text = recognize_crop(rec_model, image_rgb[top:bottom, left:right], charset)
        if text:
            lines.append((text, score, left, top, right, bottom))
    return lines


# %% ../nbs/13_ocr.ipynb #4df3604e60df
def draw_boxes(image_rgb: np.ndarray, lines: list[tuple[str, float, int, int, int, int]]) -> np.ndarray:
    "Paint a green rectangle around each recognized line."
    canvas = image_rgb.copy()
    height, width = canvas.shape[:2]
    color = np.array([32, 220, 80], np.uint8)
    for _, _, left, top, right, bottom in lines:
        x0 = int(np.clip(left, 0, width - 1))
        y0 = int(np.clip(top, 0, height - 1))
        x1 = int(np.clip(right, x0 + 1, width))
        y1 = int(np.clip(bottom, y0 + 1, height))
        thickness = 2
        canvas[y0 : y0 + thickness, x0:x1] = color
        canvas[y1 - thickness : y1, x0:x1] = color
        canvas[y0:y1, x0 : x0 + thickness] = color
        canvas[y0:y1, x1 - thickness : x1] = color
    return canvas


# %% ../nbs/13_ocr.ipynb #23cbaaf90eaf
def save_rgb(path: Path, image_rgb: np.ndarray) -> None:
    Image.fromarray(np.ascontiguousarray(image_rgb), mode="RGB").save(path)


# %% ../nbs/13_ocr.ipynb #633982e92b58
def main() -> None:
    from solid_lens.model import compile_detector, compile_recognizer

    parser = argparse.ArgumentParser(description="Run PP-OCRv6 medium OCR with MAX")
    parser.add_argument("image", type=Path)
    parser.add_argument("--output", type=Path, help="image with boxes drawn; defaults to <image>.boxes.png")
    args = parser.parse_args()
    image = load_image(args.image)
    det_h, det_w = detection_hw(*image.shape[:2])
    charset = load_charset(ROOT / "models" / "ppocrv6_dict.txt", add_space=True)
    det_cache = ROOT / "models" / f"native_medium_det_{det_h}x{det_w}.mef"
    rec_cache = ROOT / "models" / "native_medium_rec_48x320.mef"
    print(
        f"{'loading cached' if any(det_cache.glob('*.mef')) else 'compiling'} PP-OCRv6 medium detector {det_h}x{det_w}",
        file=sys.stderr,
    )
    detector = compile_detector(height=det_h, width=det_w, cache_dir=det_cache)
    print(
        "loading cached recognizer" if any(rec_cache.glob("*.mef")) else "compiling PP-OCRv6 medium recognizer",
        file=sys.stderr,
    )
    recognizer = compile_recognizer(cache_dir=rec_cache)
    lines = read_page(image, detector, recognizer, charset)
    output = args.output or args.image.with_name(f"{args.image.stem}.boxes.png")
    save_rgb(output, draw_boxes(image, lines))
    print(f"wrote {output}", file=sys.stderr)
    for text, score, *_ in lines:
        print(f"{score:.2f}  {text}")


# %% ../nbs/13_ocr.ipynb #7a3eb8767665
if __name__ == "__main__":
    main()

